version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wolfrpg"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d8cs2pyxrhbv"
s3_prefix = "wolfrpg"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
