AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wolf-rpg-random-active-character

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        WAIT_TIME: 2
        URL: 'https://wolf-rpg.com/'
        POST_MIN: 50

Resources:
  CharBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'wolfrpg-characters'
  RandomCharFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/random-char/
      Handler: randomChar.lambda_handler
      Runtime: python3.7
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub 'wolfrpg-characters'
      Events:
        RandomChar:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /random-char/api
            Method: get
  RandomCharViewFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/view/
      Handler: randomCharView.lambda_handler
      Runtime: python3.7
      Events:
        RandomChar:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /random-char
            Method: get
  GetActiveChars:
    Type: AWS::Serverless::Function
    Properties:
      Handler: activeChars.lambda_handler
      Runtime: python3.7
      CodeUri: src/active-chars/
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
      Timeout: 120
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub 'wolfrpg-characters'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RandomCharApi:
    Description: "API Gateway endpoint URL for Prod stage for Random Character function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/random-char/"
  RandomCharFunction:
    Description: "Random Character Lambda Function ARN"
    Value: !GetAtt RandomCharFunction.Arn
  GetActiveChars:
    Description: "Get Active Characters Scheduled Lambda ARN"
    Value: !GetAtt GetActiveChars.Arn
  RandomCharFunctionIamRole:
    Description: "Implicit IAM Role created for Random Character function"
    Value: !GetAtt RandomCharFunctionRole.Arn
  CharBucket:
    Description: "S3 Bucket for characters"
    Value: !GetAtt CharBucket.Arn
